### ISSUE TITLE
Wrong Timezone Used

### ISSUE THREAD

**Issue by crespire** [basecamp/local_time#166] opened 2024-04-18 14:17 UTC
I posted a comment on #158, but thought it would be wise to open as a separate issue.

I am seeing this behaviour currently where the timezone parsing is incorrect for one of 4 values:

<img width="330" alt="image" src="https://github.com/basecamp/local_time/assets/36272822/1d7943d4-1ba4-48bc-a944-b69e88328174">

Any ideas as to what could be happening? The underlying data looks okay:
Anomalous EST value:
```html
<time datetime="2023-12-14T02:02:42Z" data-local="time" data-format="%b %-d, %Y %H:%M %Z" title="December 13, 2023 at 9:02pm EST" data-processed-at="2024-04-18T14:09:10.946Z" data-localized="">Dec 13, 2023 21:02 EST</time> (4 months ago)

```

Compared with a correct EDT value:
```html
<time datetime="2024-04-04T19:42:17Z" data-local="time" data-format="%b %-d, %Y %H:%M %Z" title="April 4, 2024 at 3:42pm EDT" data-processed-at="2024-04-18T14:09:10.945Z" data-localized="">Apr 4, 2024 15:42 EDT</time> (14 days ago)
```

**Comment by josefarias** [comment] 2024-04-19 17:28
Hey @crespire,

This is intended behavior. The library is meant to display the time zone experienced by the client at the provided timestamp.

It appears you're based in Toronto (per your GH profile), which is in daylight savings time in April '24

![Browser console showing how parsing each of the provided dates natively results in different timezones, independent of LocalTime](https://github.com/basecamp/local_time/assets/31393016/df615bcb-a68a-4b9a-aff1-77a219376255)

**Comment by josefarias** [comment] 2024-04-19 17:33
Sorry, accidentally posted prematurely.

This behavior makes sense, for example, if you're displaying dates for events in a calendar. You'd want the applicable time zone shown even if you're not in that time zone currently. Or if you're looking back at a comment thread, you'd want to see the time zone which applied at the time the comment was posted — otherwise you'd have to convert the timestamp in your head in order to get an accurate picture of how events transpired. These are the kinds of use cases the library was built for.

Closing for now but let me know if you have any other questions.

**Closed by josefarias** 2024-04-19 17:33 UTC
