### ISSUE TITLE
local_time doesn't support %Z in Firefox

### ISSUE THREAD

**Issue by sloneorzeszki** [basecamp/local_time#86] opened 2019-05-09 10:34 UTC
Not sure if this is a known issue (didn't find anything):

`= local_time(@batch.scheduled_for, "%Y/%m/%d %H:%M %Z")`

Works in Chrome:
![image](https://user-images.githubusercontent.com/13190250/57447013-56c4c200-7256-11e9-9de4-48a1bfb98437.png)
but not in Firefox:
![image](https://user-images.githubusercontent.com/13190250/57447091-81af1600-7256-11e9-81fb-3e40ce0ecab7.png)

**Comment by jonmann20** [comment] 2019-12-26 20:00
%Z is working for me now in latest FF, but does not work in Windows 7 Chrome v79

**Comment by igienger** [comment] 2020-06-13 22:20
I have this issue on Chrome too

Windows 10 Pro, 19041.329
Version 83.0.4103.97 (Official Build) (64-bit)

It does not appear on Edge.

**Comment by igienger** [comment] 2020-06-13 22:28
In my case, it turns out the issue is because Chrome renders my timezone as "Hawaii-Aleutian Standard Time". The dash (-) in the middle throws off the parsing.

**Comment by josefarias** [comment] 2023-06-24 01:02
I think this might be FF returning something unexpected for the timezone name and we're not able to parse it – so we fall back to an empty string. Might take a look at this later.

**Comment by josefarias** [comment] 2023-12-05 00:04
We've changed how we parse timezones per https://github.com/basecamp/local_time/pull/142. Please, let me know if this isn't fixed on main. Thanks!

**Closed by josefarias** 2023-12-05 00:04 UTC
