### ISSUE TITLE
i18n timezones are not parsed correctly because of unicode issues or translation issues.

### ISSUE THREAD

**Issue by a-nickol** [basecamp/local_time#150] opened 2023-11-28 12:40 UTC
Non english timezones, e.g. `Fri Dec 29 2023 12:21:08 GMT+0100 (Mitteleuropäische Normalzeit)` are not parsed correctly. 

First the regex does not work, because 'ä' is no ascii char. 
Nevertheless the concatenation of the first letters of the timezone won't work either.

**Comment by josefarias** [comment] 2023-11-28 14:33
Thanks @a-nickol, could you confirm if it's parsed correctly in [this](https://github.com/basecamp/local_time/pull/142) branch, please? It's a work-in-progress PR that's near completion.

**Comment by a-nickol** [comment] 2023-11-28 16:36
The tests work on my machine, yes.

**Comment by josefarias** [comment] 2023-11-28 17:47
@a-nickol Thanks for checking. Just to make sure, when you say the tests work do you mean running the full automated test suite or did you perform the manual check on localhost:9000 (a new addition in that PR)? Or possibly both?

Only the manual check would've caught any regressions re: your local timezone.

**Comment by a-nickol** [comment] 2023-11-28 17:52
I executed 'rake test' and called the new route. I haven't checked the result or semantics of the route in detail, but more importantly the automatic test suite passed compared to the main branch which fails because of timezone issues.

**Comment by josefarias** [comment] 2023-11-28 18:03
Ah I see I thought the test suite would pass. Perfect, thanks for confirming.

**Comment by josefarias** [comment] 2023-12-01 19:39
https://github.com/basecamp/local_time/pull/142 has been merged so this should be fixed on `main` now. Thanks again.

**Closed by josefarias** 2023-12-01 19:39 UTC

**Comment by a-nickol** [comment] 2023-12-02 10:34
The tests fail now, e.g.

```
strftime time zones: time zones Intl can't abbreviate are parsed by our heuristic
'GMT+7' doesn't look like a timezone. System date: 'Sat Dec 02 2023 11:32:44 GMT+0100 (Mitteleuropäische Normalzeit)'
```

**Comment by josefarias** [comment] 2023-12-02 11:07
@a-nickol Ah, that's from a new test that actually might not be worth keeping around. I'll take a look today. If you don't mind, could you share which country you're in and which language you're using in your browser? Thanks!

**Comment by josefarias** [comment] 2023-12-02 11:08
Also, please let me know if any other tests fail as well.

**Comment by a-nickol** [comment] 2023-12-02 11:27
I am in Germany, language is German. We have currently winter time, this is CET.

**Comment by a-nickol** [comment] 2023-12-02 11:30
Every second execution all timezone tests are fail because GMT+7 is not accepted by the timezone assertions. Maybe mock or stub is not restored. 

Maybe I have later time to check too

**Comment by a-nickol** [comment] 2023-12-02 13:45
@josefarias `stub.restore()` is missing on line 107

**Comment by a-nickol** [comment] 2023-12-02 14:09
The mock sets the data accordingly which used later and then fails:  
```
      if options.timeZoneName == "long"
        "Thu Nov 30 2023 14:22:57 GMT+0700 (Central Twilight Time)" # not a known edge-case
      else if options.timeZoneName == "short"
        "11/30/2023, 2:22:57 PM GMT+7" # not possible to abbreviate
```

Error:
```
'GMT+7' doesn't look like a timezone. 
```

**Comment by josefarias** [comment] 2023-12-02 23:42
Thanks @a-nickol, great digging. The root cause was that we weren't completely stubbing the current timezone in the failing test. Should be fixed by https://github.com/basecamp/local_time/pull/154, so tests should be passing for you on `main` once merged.

> Maybe a mock or stub is not restored.

Right, the tests were fragile in this regard. I've also gone ahead and improved that in the same PR.
