### ISSUE TITLE
Get last user's Time Zone and store it in database ...

### ISSUE THREAD

**Issue by jhovad** [basecamp/local_time#83] opened 2018-09-07 12:01 UTC
For my purpose is important that administrator of the app will see last user's timezone ... Is it possible to get user's timezone somehow into controller and store in users profile ... ?
Very essencital for me ... O:)
THX!!

**Comment by orhantoy** [comment] 2018-10-03 22:55
This seems unrelated to the `local_time` gem, as well as #64 which appears to be a duplicate of this issue.

But to answer your question, I think you could do something like writing the value of `new Date().getTimezoneOffset()` to a hidden field which will get submitted possibly alongside some other fields. If you need more help I would be happy to help out on a better suited platform like stackoverflow.

**Comment by CodyFitzpatrick** [comment] 2019-03-21 23:53
@jhovad It seems like you're looking for a cross between https://gorails.com/episodes/auto-detect-user-time-zones-in-rails and http://railscasts.com/episodes/106-time-zones-in-rails-2-1. Those resources (and others found via your favorite search engine) should be sufficient for you to piece together your desired solution.

**Closed** 2022-02-01 20:12 UTC
